### ISSUE TITLE
Can this be used to disable/replace Win10 memory caching completely?

### ISSUE THREAD

**Issue by DwarfFighterCleric** [JaCraig/DragonHoard#1]
I'm searching for how to minimize or fine-tune Windows 10's default Memory Cache or Standby Cache mechanisms.  
This is the temporary workaround I found so far:  
https://github.com/thecarnie/CacheMon/issues/2#issue-1236564043  
  
Can this tool be used to disable Win10's native memory caching mechanism at all?  
How could I achieve that?  
  
Another alternative would be simply setting up a Hard Limit for how big Standby Cache can grow, that would suffice all my needs (avoid situations where Windows starts writing heavily to pagefile, because I cannot disable pagefile entirely due to some heavy applications that overcommit memory)  
Do you know how can I set a hard limit inside Windows 10 system itself?  
I am surprised to find Microsoft never provided documentation about this.

**Comment by JaCraig** [comment]
This a replacement for ASP.Net MVC's built in cache, not something to replace any OS level caching.
